
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Siswa      <small><?= cclang('detail', ['Siswa']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/siswa'); ?>">Siswa</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Siswa</h3>
                     <h5 class="widget-user-desc">Detail Siswa</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_siswa" id="form_siswa" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Siswa </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->id_siswa); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NIPD </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->nipd); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Password </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->pass); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Siswa </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->nama); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Kelamin </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->jenis_kelamin); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NISN </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->nisn); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tempat Lahir </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->tempat_lahir); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Lahir </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->tanggal_lahir); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NIK </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->nik); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Agama </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->agama); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kebutuhan Khusus </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->kebutuhan_khusus); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alamat </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->alamat); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RT </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->rt); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RW </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->rw); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Dusun </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->dusun); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Desa/Kelurahan </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->kelurahan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kecamatan </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->kecamatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Pos </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->kode_pos); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Tinggal </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->jenis_tinggal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alat Transportasi </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->alat_transportasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Telepon </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->telepon); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">HP </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->hp); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email Aktif </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SKHUN </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->skhun); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Penerima KPS </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->penerima_kps); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No. KPS </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->no_kps); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Foto </label>
                        <div class="col-sm-8">
                             <?php if (is_image($siswa->foto)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/siswa/' . $siswa->foto; ?>">
                                <img src="<?= BASE_URL . 'uploads/siswa/' . $siswa->foto; ?>" class="image-responsive" alt="image siswa" title="foto siswa" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/siswa/' . $siswa->foto; ?>">
                                 <img src="<?= get_icon_file($siswa->foto); ?>" class="image-responsive" alt="image siswa" title="foto <?= $siswa->foto; ?>" width="40px"> 
                               <?= $siswa->foto ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->nama_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tahun Lahir Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->tahun_lahir_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pendidikan Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->pendidikan_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pekerjaan Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->pekerjaan_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Penghasilan Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->penghasilan_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kebutuhan Khusus Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->kebutuhan_khusus_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No. Telepon Ayah </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->no_telpon_ayah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->nama_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tahun Lahir Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->tahun_lahir_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pendidikan Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->pendidikan_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pekerjaan Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->pekerjaan_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Penghasilan Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->penghasilan_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kebutuhan Khusus Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->kebutuhan_khusus_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No. Telepon Ibu </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->no_telpon_ibu); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Wali </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->nama_wali); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tahun Lahir Wali </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->tahun_lahir_wali); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pendidikan Wali </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->pendidikan_wali); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pekerjaan Wali </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->pekerjaan_wali); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Penghasilan Wali </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->penghasilan_wali); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Angkatan/Tahun Masuk </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->angkatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Awal </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->status_awal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Keaktifan </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->status_keaktifan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tingkat </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->tingkat); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kelas </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->nama_kelas); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jurusan </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->kode_jurusan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sesi </label>

                        <div class="col-sm-8">
                           <?= _ent($siswa->id_sesi); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('siswa_update', function() use ($siswa){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit siswa (Ctrl+e)" href="<?= site_url('administrator/siswa/edit/'.$siswa->id_siswa); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Siswa']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/siswa/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Siswa']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
