
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Jenis Tinggal      <small><?= cclang('detail', ['Jenis Tinggal']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/jenis_tinggal'); ?>">Jenis Tinggal</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Jenis Tinggal</h3>
                     <h5 class="widget-user-desc">Detail Jenis Tinggal</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_jenis_tinggal" id="form_jenis_tinggal" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Jenistinggal </label>

                        <div class="col-sm-8">
                           <?= _ent($jenis_tinggal->id_jenistinggal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Tinggal </label>

                        <div class="col-sm-8">
                           <?= _ent($jenis_tinggal->jenis_tinggal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Keterangan </label>

                        <div class="col-sm-8">
                           <?= _ent($jenis_tinggal->keterangan); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('jenis_tinggal_update', function() use ($jenis_tinggal){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit jenis_tinggal (Ctrl+e)" href="<?= site_url('administrator/jenis_tinggal/edit/'.$jenis_tinggal->id_jenistinggal); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Jenis Tinggal']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/jenis_tinggal/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Jenis Tinggal']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
