
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Rapot Pbp      <small><?= cclang('detail', ['Rapot Pbp']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/rapot_pbp'); ?>">Rapot Pbp</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Rapot Pbp</h3>
                     <h5 class="widget-user-desc">Detail Rapot Pbp</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_rapot_pbp" id="form_rapot_pbp" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Rapot Pbp </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->id_rapot_pbp); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Siswa </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->nama); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Semester </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->semester); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pilar 1 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->id_pilar_pbp_1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Catatan Pilar 1 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->catatan_pbp_1); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pilar 2 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->id_pilar_pbp_2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Catatan Pilar 2 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->catatan_pbp_2); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pilar 3 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->id_pilar_pbp_3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Catatan Pilar 3 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->catatan_pbp_3); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pilar 4 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->id_pilar_pbp_4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Catatan Pilar 4 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->catatan_pbp_4); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pilar 5 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->id_pilar_pbp_5); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Catatan Pilar 5 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->catatan_pbp_5); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pilar 6 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->id_pilar_pbp_6); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Catatan Pilar 6 </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->catatan_pbp_6); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->tanggal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Wali Kelas </label>

                        <div class="col-sm-8">
                           <?= _ent($rapot_pbp->id_guru); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('rapot_pbp_update', function() use ($rapot_pbp){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit rapot_pbp (Ctrl+e)" href="<?= site_url('administrator/rapot_pbp/edit/'.$rapot_pbp->id_rapot_pbp); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Rapot Pbp']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/rapot_pbp/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Rapot Pbp']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
