
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Isian_amatan/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Isian Amatan<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Isian Amatan</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('isian_amatan_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Isian Amatan']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/isian_amatan/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Isian Amatan']); ?></a>
                        <?php }) ?>
                        <?php is_allowed('isian_amatan_import', function(){?>
                        <a class="btn btn-flat btn-success" title="Import Isian Amatan" href="<?= site_url('administrator/isian_amatan/import'); ?>"><i class="fa fa-file-excel-o" ></i> Import XLS</a>
                        <?php }) ?>
                        <?php is_allowed('isian_amatan_rekap', function(){?>
                        <a class="btn btn-flat btn-success" title="Rekap Amatan" href="<?= site_url('administrator/isian_amatan/rekap'); ?>"><i class="fa fa-file-excel-o" ></i> Rekap Amatan</a>
                        <?php }) ?>
                        <?php is_allowed('isian_amatan_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Isian Amatan" href="<?= site_url('administrator/isian_amatan/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('isian_amatan_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Isian Amatan" href="<?= site_url('administrator/isian_amatan/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Isian Amatan</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Isian Amatan']); ?>  <i class="label bg-yellow"><?= $isian_amatan_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_isian_amatan" id="form_isian_amatan" action="<?= base_url('administrator/isian_amatan/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Tanggal</th>
                           <th>Jam</th>
                           <th>Minggu Ke-</th>
                           <th>Sekolah</th>
                           <th>Kelas</th>
                           <th>Nama Siswa</th>
                           <th>Prilaku Yang Diamati</th>
                           <th>Kode Indikator Amatan</th>
                           <th>Status Amatan</th>
                           <th>Lokasi Amatan</th>
                           <th>Pengamat</th>
                           <th>Nama Pengamat</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_isian_amatan">
                     <?php foreach($isian_amatans as $isian_amatan): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $isian_amatan->id_isian_amatan; ?>">
                           </td>
                           
                           <td><?= date("d-m-Y", strtotime(_ent($isian_amatan->tanggal))); ?></td> 
                           <td><?= date("H:i:s", strtotime(_ent($isian_amatan->jam))) ; ?></td> 
                           <td><?= _ent($isian_amatan->minggu_ke); ?></td>
                             
                           <td><?= _ent($isian_amatan->kode_sekolah); ?></td>
                           <td><?= _ent($isian_amatan->kelas); ?></td>
                             
                           <td><?= _ent($isian_amatan->nama); ?></td>
                           <td><?= _ent($isian_amatan->isi_amatan); ?></td>
                             
                           <td><?= _ent($isian_amatan->kode_indikator); ?></td>
                             
                           <td><?= _ent($isian_amatan->nama_status_amatan); ?></td>
                           <td><?= _ent($isian_amatan->nama_lokasi); ?></td>
                             
                           <td><?= _ent($isian_amatan->jenis_pengamat); ?></td>
                             
                           <td><?= _ent($isian_amatan->nama_pengamat); ?></td> 
                           <td width="200">
                              <?php is_allowed('isian_amatan_view', function() use ($isian_amatan){?>
                              <a href="<?= site_url('administrator/isian_amatan/view/' . $isian_amatan->id_isian_amatan); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('isian_amatan_update', function() use ($isian_amatan){?>
                              <a href="<?= site_url('administrator/isian_amatan/edit/' . $isian_amatan->id_isian_amatan); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('isian_amatan_delete', function() use ($isian_amatan){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/isian_amatan/delete/' . $isian_amatan->id_isian_amatan); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($isian_amatan_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Isian Amatan data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                           <!-- <option <?= $this->input->get('f') == 'tanggal' ? 'selected' :''; ?> value="tanggal">Tanggal</option>
                           <option <?= $this->input->get('f') == 'jam' ? 'selected' :''; ?> value="jam">Jam</option>
                           <option <?= $this->input->get('f') == 'minggu' ? 'selected' :''; ?> value="minggu">Minggu</option>
                           <option <?= $this->input->get('f') == 'id_kodesekolah' ? 'selected' :''; ?> value="id_kodesekolah">Id Kodesekolah</option>
                           <option <?= $this->input->get('f') == 'id_siswa' ? 'selected' :''; ?> value="id_siswa">Id Siswa</option>
                           <option <?= $this->input->get('f') == 'id_indikator_pbp' ? 'selected' :''; ?> value="id_indikator_pbp">Id Indikator Pbp</option>
                           <option <?= $this->input->get('f') == 'id_lokasi_amatan' ? 'selected' :''; ?> value="id_lokasi_amatan">Id Lokasi Amatan</option>
                           <option <?= $this->input->get('f') == 'id_jenis_pengamat' ? 'selected' :''; ?> value="id_jenis_pengamat">Id Jenis Pengamat</option>
                           <option <?= $this->input->get('f') == 'id_pengamat' ? 'selected' :''; ?> value="id_pengamat">Id Pengamat</option> -->
                           <option <?= $this->input->get('f') == 'nama' ? 'selected' :''; ?> value="nama">Nama Siswa</option>
                           <option <?= $this->input->get('f') == 'nama_rombel' ? 'selected' :''; ?> value="nama_rombel">Nama Rombel</option>
                           <option <?= $this->input->get('f') == 'nama_guru' ? 'selected' :''; ?> value="nama_guru">Nama Pengamat</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/isian_amatan');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_isian_amatan').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/isian_amatan/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>