
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Isian Amatan      <small><?= cclang('detail', ['Isian Amatan']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/isian_amatan'); ?>">Isian Amatan</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Isian Amatan</h3>
                     <h5 class="widget-user-desc">Detail Isian Amatan</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_isian_amatan" id="form_isian_amatan" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Isian Amatan </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->id_isian_amatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->tanggal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jam </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->jam); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Minggu Ke-</label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->minggu_ke); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Sekolah </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->kode_sekolah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Siswa </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->nama); ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Prilaku Yang Diamati </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->isi_amatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Indikator Amatan </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->kode_indikator); ?>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Amatan </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->nama_status_amatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Lokasi Amatan </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->nama_lokasi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pengamat </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->jenis_pengamat); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Pengamat </label>

                        <div class="col-sm-8">
                           <?= _ent($isian_amatan->nama_pengamat); ?>
                        </div>
                    </div>
                                            
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('isian_amatan_update', function() use ($isian_amatan){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit isian_amatan (Ctrl+e)" href="<?= site_url('administrator/isian_amatan/edit/'.$isian_amatan->id_isian_amatan); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Isian Amatan']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/isian_amatan/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Isian Amatan']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
