
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Tindakan_bk/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Monitoring PBP<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Monitoring PBP</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Isian Amatan']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/tindakan_bk/view_amatan/' . $id_kodesekolah .'/'. $id_rombel .'/'. $id_semester); ?>"><i class="fa fa-arrow-circle-left" ></i> Kemabli Ke List</a>

                        <?php is_allowed('tindakan_bk_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Tindakan Bk']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/tindakan_bk/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Tindakan Bk']); ?></a>
                        <?php }) ?>
                        <?php is_allowed('tindakan_bk_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Tindakan Bk" href="<?= site_url('administrator/tindakan_bk/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('tindakan_bk_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Tindakan Bk" href="<?= site_url('administrator/tindakan_bk/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Monitoring PBP</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Tindakan Bk']); ?>  <i class="label bg-yellow"> <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tindakan_bk" id="form_tindakan_bk" action="<?= base_url('administrator/tindakan_bk/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>NO</th>
                           <th>Tanggal</th>
                           <th>Jam</th>
                           <th>Minggu Ke-</th>
                           <th>Sekolah</th>
                           <th>Kelas</th>
                           <th>Nama Siswa</th>
                           <th>Prilaku Yang Diamati</th>
                           <th>Kode Indikator Amatan</th>
                           <th>Status Amatan</th>
                           <th>Lokasi Amatan</th>
                           <th>Pengamat</th>
                           <th>Nama Pengamat</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_isian_amatan">
                        <?php $no=1; foreach($isian_amatan_bk_details as $isian_amatan_bk_detail): ?>
                        <tr>
                           <td><?= _ent($no++); ?></td>
                           
                           <td><?= date("d-m-Y", strtotime(_ent($isian_amatan_bk_detail->tanggal))); ?></td> 
                           <td><?= date("H:i:s", strtotime(_ent($isian_amatan_bk_detail->jam))) ; ?></td> 
                           <td><?= _ent($isian_amatan_bk_detail->minggu_ke); ?></td>
                             
                           <td><?= _ent($isian_amatan_bk_detail->kode_sekolah); ?></td>
                           <td><?= _ent($isian_amatan_bk_detail->kelas); ?></td>
                             
                           <td><?= _ent($isian_amatan_bk_detail->nama); ?></td>
                           <td><?= _ent($isian_amatan_bk_detail->isi_amatan); ?></td>
                             
                           <td><?= _ent($isian_amatan_bk_detail->kode_indikator); ?></td>
                             
                           <td><?= _ent($isian_amatan_bk_detail->nama_status_amatan); ?></td>
                           <td><?= _ent($isian_amatan_bk_detail->nama_lokasi); ?></td>
                             
                           <td><?= _ent($isian_amatan_bk_detail->jenis_pengamat); ?></td>
                             
                           <td><?= _ent($isian_amatan_bk_detail->nama_pengamat); ?></td> 
                        </tr>
                      <?php endforeach; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Tindakan BK</h3>
                     <h5 class="widget-user-desc">List Tindakan BK</h5>
                     <hr>
                  </div>

                  <!-- table -->
                <div class="table-responsive">
                  <table class="table table-bordered table-striped dataTable">
                    <thead>
                      <tr class="">
                        <th width="5%">No.</th>
                        <th width="15%">Tanggal</th>
                        <!-- <th>Nama Siswa</th> -->
                        <th>Isi Tindakan</th>
                        <th width="15%">Nama BK</th>
                      </tr>
                    </thead>
                    <tbody id="tbody_rombel">
                      <?php $no = 1; ?>
                      <?php foreach ($tindakan_bks as $tindakan) : ?>
                        <tr>
                          <td><?= $no++; ?></td>
                          <td><?= _ent($tindakan->tanggal); ?></td>
                          <!-- <td><?= _ent($tindakan->id_siswa); ?></td> -->
                          <td><?= _ent($tindakan->isi_tindakan); ?></td>
                          <td><?= _ent($tindakan->nama_bk); ?></td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($tindakan_bk_counts == 0) : ?>
                        <tr>
                          <td colspan="100">
                            Tindakan BK data is not available (Kosong)
                          </td>
                        </tr>
                      <?php endif; ?>
                    </tbody>
                  </table>
                </div>
                <!-- tutup table -->
                
               <!-- /.widget-user -->
               <div class="row">
                  
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tindakan_bk').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tindakan_bk/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>