
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Tindakan_bk/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Monitoring PBP<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Monitoring PBP</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <form name="" id="" action="<?= base_url('administrator/tindakan_bk/index'); ?>">
                          <?php
                            $querySemester =  $this->db->query('SELECT *
                                              FROM semester
                                              JOIN periode ON periode.id_periode = semester.id_periode');
                            $sqlSemseter = $querySemester->result();
                          ?>
                          
                          <select class="form-control chosen chosen-select-deselect" name="id_semester" id="id_semester" data-placeholder="Pilih Semester" >
                              <option value=""></option>
                              <?php foreach ($sqlSemseter as $row): ?>
                                <option value="<?= $row->id_semester ?>"><?= $row->periode ." ". $row->semester; ?></option>
                              <?php endforeach; ?>  
                          </select>

                          <button type="submit" class="btn btn-flat btn-success" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                          Filter
                          </button>

                        </form>

                        <?php is_allowed('tindakan_bk_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Tindakan Bk']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/tindakan_bk/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Tindakan Bk']); ?></a>
                        <?php }) ?>
                       
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Monitoring PBP</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Tindakan Bk']); ?>  <i class="label bg-yellow"><?= $tindakan_bk_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tindakan_bk" id="form_tindakan_bk" action="<?= base_url('administrator/tindakan_bk/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <!-- <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th> -->
                           <th>No.</th>
                           <th>Kode Sekolah</th>
                           <th>Total Amatan</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_tindakan_bk">
                     <?php $no = 1; foreach($tindakan_bks as $tindakan_bk): ?>
                        <tr>
                           <td><?= _ent($no++); ?>
                           <td><?= _ent($tindakan_bk->kode_sekolah); ?>
                           <td><?= _ent($tindakan_bk->total_amatan); ?>
                           <td width="200">
                               <a href="<?= site_url('administrator/tindakan_bk/view_rombel/' . $tindakan_bk->id_kodesekolah . '/' . $id_semester); ?>" class="label-default"><i class="fa fa-newspaper-o"> </i> Lihat Detail </a>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($tindakan_bk_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Tindakan Bk data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                           <!-- <option <?= $this->input->get('f') == 'tanggal' ? 'selected' :''; ?> value="tanggal">Tanggal</option>
                           <option <?= $this->input->get('f') == 'id_siswa' ? 'selected' :''; ?> value="id_siswa">Id Siswa</option>
                           <option <?= $this->input->get('f') == 'isi_tindakan' ? 'selected' :''; ?> value="isi_tindakan">Isi Tindakan</option>
                           <option <?= $this->input->get('f') == 'id_guru_bk' ? 'selected' :''; ?> value="id_guru_bk">Id Guru Bk</option> -->
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/tindakan_bk');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){

    
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tindakan_bk').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tindakan_bk/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>