
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Akd Jurnal Guru      <small><?= cclang('detail', ['Akd Jurnal Guru']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/akd_jurnal_guru'); ?>">Akd Jurnal Guru</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Akd Jurnal Guru</h3>
                     <h5 class="widget-user-desc">Detail Akd Jurnal Guru</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_akd_jurnal_guru" id="form_akd_jurnal_guru" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Jurnal </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->id_jurnal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Jadwal </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->kode_jadwal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Hari </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->hari); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->tanggal); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jam Ke </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->jam_ke); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Materi </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->materi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kompetensi Dasar </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->kompetensi_dasar); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kegiatan </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->kegiatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Media Pembelajaran </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->media_pembelajaran); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sumber Belajar </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->sumber_belajar); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Keterangan </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->keterangan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Waktu Input </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->waktu_input); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sekolah </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jurnal_guru->kode_sekolah); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('akd_jurnal_guru_update', function() use ($akd_jurnal_guru){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit akd_jurnal_guru (Ctrl+e)" href="<?= site_url('administrator/akd_jurnal_guru/edit/'.$akd_jurnal_guru->id_jurnal); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Akd Jurnal Guru']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/akd_jurnal_guru/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Akd Jurnal Guru']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
