<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
    //This page is a result of an autogenerated content made by running test.html with firefox.
    function domo() {

        // Binding keys
        $('*').bind('keydown', 'Ctrl+a', function assets() {
            window.location.href = BASE_URL + '/administrator/Rombel/add';
            return false;
        });

        $('*').bind('keydown', 'Ctrl+f', function assets() {
            $('#sbtn').trigger('click');
            return false;
        });

        $('*').bind('keydown', 'Ctrl+x', function assets() {
            $('#reset').trigger('click');
            return false;
        });

        $('*').bind('keydown', 'Ctrl+b', function assets() {

            $('#reset').trigger('click');
            return false;
        });
    }

    jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Rombel<small><?= cclang('list_all'); ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Rombel</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">

        <div class="col-md-12">
            <div class="box box-warning">
                <div class="box-body ">
                    <!-- Widget: user widget style 1 -->
                    <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="widget-user-header ">
                            <div class="row pull-right">
                                <?php is_allowed('rombel_add', function () { ?>
                                    <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Rombel']); ?>  (Ctrl+a)" href="<?= site_url('administrator/rombel/add'); ?>"><i class="fa fa-plus-square-o"></i> <?= cclang('add_new_button', ['Rombel']); ?></a>
                                <?php }) ?>
                                <?php is_allowed('rombel_export', function () { ?>
                                    <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Rombel" href="<?= site_url('administrator/rombel/export'); ?>"><i class="fa fa-file-excel-o"></i> <?= cclang('export'); ?> XLS</a>
                                <?php }) ?>
                                <?php is_allowed('rombel_export', function () { ?>
                                    <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Rombel" href="<?= site_url('administrator/rombel/export_pdf'); ?>"><i class="fa fa-file-pdf-o"></i> <?= cclang('export'); ?> PDF</a>
                                <?php }) ?>
                            </div>
                            <div class="widget-user-image">
                                <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                            </div>
                            <!-- /.widget-user-image -->
                            <h3 class="widget-user-username">Rombel</h3>
                            <h5 class="widget-user-desc"><?= cclang('list_all', ['Rombel']); ?> <i class="label bg-yellow"><?= $rombel_counts; ?> <?= cclang('items'); ?></i></h5>
                        </div>

                        <form name="form_rombel" id="form_rombel" action="<?= base_url('administrator/rombel/index'); ?>">


                            <div class="table-responsive">
                                <table class="table table-bordered table-striped dataTable">
                                    <thead>
                                        <tr class="">
                                            <th>
                                                <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                                            </th>
                                            <th>Kode Sekolah</th>
                                            <th>Periode</th>
                                            <th>Nama Rombel</th>
                                            <th>Wali Kelas</th>
                                            <th>Kelas</th>
                                            <th>Jumlah Siswa</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tbody_rombel">
                                        <?php foreach ($rombels as $rombel) : ?>
                                            <tr>
                                                <td width="5">
                                                    <input type="checkbox" class="flat-red check" name="id[]" value="<?= $rombel->id_rombel; ?>">
                                                </td>
                                                <?php
                                                $sql = $this->db->where('id_rombel', $rombel->id_rombel);
                                                $resultsql = $this->db->count_all_results('detail_rombel');
                                                ?>
                                                <td><?= _ent($rombel->kode_sekolah); ?></td>
                                                <td><?= _ent($rombel->periode); ?></td>
                                                <td><?= _ent($rombel->nama_rombel); ?></td>
                                                <td><?= _ent($rombel->nama_guru); ?></td>
                                                <td><?= _ent($rombel->nama_kelas); ?></td>
                                                <td><?= _ent($resultsql); ?></td>


                                                <td width="200">
                                                    <?php is_allowed('rombel_view', function () use ($rombel) { ?>
                                                        <a href="<?= site_url('administrator/detail_rombel/add/' . $rombel->id_rombel); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> Detail
                                                        <?php }) ?>
                                                        <br>
                                                        <?php is_allowed('rombel_view', function () use ($rombel) { ?>
                                                            <a href="<?= site_url('administrator/akd_jadwal_pelajaran/view/' . $rombel->id_rombel); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= "Jadwal Pelajaran"; ?>
                                                            <?php }) ?>
                                                            <br>
                                                            <?php is_allowed('rombel_update', function () use ($rombel) { ?>
                                                                <a href="<?= site_url('administrator/rombel/edit/' . $rombel->id_rombel); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                                                            <?php }) ?>
                                                            <?php is_allowed('rombel_delete', function () use ($rombel) { ?>
                                                                <a href="javascript:void(0);" data-href="<?= site_url('administrator/rombel/delete/' . $rombel->id_rombel); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                                                            <?php }) ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                        <?php if ($rombel_counts == 0) : ?>
                                            <tr>
                                                <td colspan="100">
                                                    Rombel data is not available
                                                </td>
                                            </tr>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                            </div>
                    </div>
                    <hr>
                    <!-- /.widget-user -->
                    <div class="row">
                        <div class="col-md-8">
                            <div class="col-sm-2 padd-left-0 ">
                                <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email">
                                    <option value="">Bulk</option>
                                    <option value="delete">Delete</option>
                                </select>
                            </div>
                            <div class="col-sm-2 padd-left-0 ">
                                <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                            </div>
                            <div class="col-sm-3 padd-left-0  ">
                                <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                            </div>
                            <div class="col-sm-3 padd-left-0 ">
                                <select type="text" class="form-control chosen chosen-select" name="f" id="field">
                                    <option value=""><?= cclang('all'); ?></option>
                                    <option <?= $this->input->get('f') == 'kode_sekolah' ? 'selected' : ''; ?> value="kode_sekolah">Kode Sekolah</option>
                                    <option <?= $this->input->get('f') == 'kode_jurusan' ? 'selected' : ''; ?> value="kode_jurusan">Kode Jurusan</option>
                                    <option <?= $this->input->get('f') == 'nama_rombel' ? 'selected' : ''; ?> value="nama_rombel">Nama Rombel</option>
                                    <option <?= $this->input->get('f') == 'wali_kelas' ? 'selected' : ''; ?> value="wali_kelas">Wali Kelas</option>
                                    <option <?= $this->input->get('f') == 'kelas' ? 'selected' : ''; ?> value="kelas">Kelas</option>
                                    <option <?= $this->input->get('f') == 'periode' ? 'selected' : ''; ?> value="periode">Periode</option>
                                </select>
                            </div>
                            <div class="col-sm-1 padd-left-0 ">
                                <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                                    Filter
                                </button>
                            </div>
                            <div class="col-sm-1 padd-left-0 ">
                                <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/rombel'); ?>" title="<?= cclang('reset_filter'); ?>">
                                    <i class="fa fa-undo"></i>
                                </a>
                            </div>
                        </div>
                        </form>
                        <div class="col-md-4">
                            <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate">
                                <?= $pagination; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <!--/box body -->
            </div>
            <!--/box -->
        </div>
    </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
    $(document).ready(function() {

        $('.remove-data').click(function() {

            var url = $(this).attr('data-href');

            swal({
                    title: "<?= cclang('are_you_sure'); ?>",
                    text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
                    cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
                    closeOnConfirm: true,
                    closeOnCancel: true
                },
                function(isConfirm) {
                    if (isConfirm) {
                        document.location.href = url;
                    }
                });

            return false;
        });


        $('#apply').click(function() {

            var bulk = $('#bulk');
            var serialize_bulk = $('#form_rombel').serialize();

            if (bulk.val() == 'delete') {
                swal({
                        title: "<?= cclang('are_you_sure'); ?>",
                        text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
                        cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
                        closeOnConfirm: true,
                        closeOnCancel: true
                    },
                    function(isConfirm) {
                        if (isConfirm) {
                            document.location.href = BASE_URL + '/administrator/rombel/delete?' + serialize_bulk;
                        }
                    });

                return false;

            } else if (bulk.val() == '') {
                swal({
                    title: "Upss",
                    text: "<?= cclang('please_choose_bulk_action_first'); ?>",
                    type: "warning",
                    showCancelButton: false,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Okay!",
                    closeOnConfirm: true,
                    closeOnCancel: true
                });

                return false;
            }

            return false;

        }); /*end appliy click*/


        //check all
        var checkAll = $('#check_all');
        var checkboxes = $('input.check');

        checkAll.on('ifChecked ifUnchecked', function(event) {
            if (event.type == 'ifChecked') {
                checkboxes.iCheck('check');
            } else {
                checkboxes.iCheck('uncheck');
            }
        });

        checkboxes.on('ifChanged', function(event) {
            if (checkboxes.filter(':checked').length == checkboxes.length) {
                checkAll.prop('checked', 'checked');
            } else {
                checkAll.removeProp('checked');
            }
            checkAll.iCheck('update');
        });

    }); /*end doc ready*/
</script>