
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Akd Jadwal Jam Ke      <small><?= cclang('detail', ['Akd Jadwal Jam Ke']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/akd_jadwal_jam_ke'); ?>">Akd Jadwal Jam Ke</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Akd Jadwal Jam Ke</h3>
                     <h5 class="widget-user-desc">Detail Akd Jadwal Jam Ke</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_akd_jadwal_jam_ke" id="form_akd_jadwal_jam_ke" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Jam Ke </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jadwal_jam_ke->id_jam_ke); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode Sekolah </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jadwal_jam_ke->kode_sekolah); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jam Ke </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jadwal_jam_ke->jam_ke); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jam Mulai </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jadwal_jam_ke->jam_mulai); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jam Selesai </label>

                        <div class="col-sm-8">
                           <?= _ent($akd_jadwal_jam_ke->jam_selesai); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('akd_jadwal_jam_ke_update', function() use ($akd_jadwal_jam_ke){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit akd_jadwal_jam_ke (Ctrl+e)" href="<?= site_url('administrator/akd_jadwal_jam_ke/edit/'.$akd_jadwal_jam_ke->id_jam_ke); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Akd Jadwal Jam Ke']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/akd_jadwal_jam_ke/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Akd Jadwal Jam Ke']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
