<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
    //This page is a result of an autogenerated content made by running test.html with firefox.
    function domo() {

        // Binding keys
        $('*').bind('keydown', 'Ctrl+a', function assets() {
            window.location.href = BASE_URL + '/administrator/Akd_jadwal_pelajaran/add';
            return false;
        });

        $('*').bind('keydown', 'Ctrl+f', function assets() {
            $('#sbtn').trigger('click');
            return false;
        });

        $('*').bind('keydown', 'Ctrl+x', function assets() {
            $('#reset').trigger('click');
            return false;
        });

        $('*').bind('keydown', 'Ctrl+b', function assets() {

            $('#reset').trigger('click');
            return false;
        });
    }

    jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Jadwal Pelajaran<small><?= cclang('list_all'); ?></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Jadwal Pelajaran</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">

        <div class="col-md-12">
            <div class="box box-warning">
                <div class="box-body ">
                    <!-- Widget: user widget style 1 -->
                    <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="widget-user-header ">
                            <div class="row pull-right">
                                <?php is_allowed('akd_jadwal_pelajaran_add', function () { ?>
                                    <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Akd Jadwal Pelajaran']); ?>  (Ctrl+a)" href="<?= site_url(
                                                                                                                                                                                            'administrator/akd_jadwal_pelajaran/add_by/' . $this->uri->segment(4)
                                                                                                                                                                                        ); ?>"><i class="fa fa-plus-square-o"></i> <?= cclang('add_new_button', ['Akd Jadwal Pelajaran']); ?></a>
                                <?php }) ?>
                                <?php is_allowed('akd_jadwal_pelajaran_export', function () { ?>
                                    <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Akd Jadwal Pelajaran" href="<?= site_url('administrator/akd_jadwal_pelajaran/export'); ?>"><i class="fa fa-file-excel-o"></i> <?= cclang('export'); ?> XLS</a>
                                <?php }) ?>
                                <?php is_allowed('akd_jadwal_pelajaran_export', function () { ?>
                                    <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Akd Jadwal Pelajaran" href="<?= site_url('administrator/akd_jadwal_pelajaran/export_pdf'); ?>"><i class="fa fa-file-pdf-o"></i> <?= cclang('export'); ?> PDF</a>
                                <?php }) ?>
                            </div>
                            <div class="widget-user-image">
                                <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                            </div>
                            <!-- /.widget-user-image -->
                            <!-- <?php var_dump($rombel->nama_rombel); ?> -->
                            <h3 class="widget-user-username">Jadwal Pelajaran </h3>
                            <h5 class="widget-user-desc"><?= cclang('list_all', ['Akd Jadwal Pelajaran']); ?> <i class="label bg-yellow"><?= $akd_jadwal_pelajaran_counts; ?> <?= cclang('items'); ?></i></h5>
                        </div>

                        <form name="form_akd_jadwal_pelajaran" id="form_akd_jadwal_pelajaran" action="<?= base_url('administrator/akd_jadwal_pelajaran/index'); ?>">


                            <div class="table-responsive">
                                <table class="table table-bordered table-striped dataTable">
                                    <thead>
                                        <tr class="">
                                            <th>
                                                <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                                            </th>
                                            <th>Tahun Ajaran/Semester</th>
                                            <th>Kode Guru Pengajar</th>
                                            <th>Rombongan Belajar</th>
                                            <th>Mata Pelajaran</th>
                                            <th>Ruangan</th>
                                            <th>Guru Pengajar</th>
                                            <!-- <th>Paralel</th>
                           <th>Jadwal Serial</th> -->
                                            <th>Mulai Jam Ke</th>
                                            <th>Berakhir Jam Ke</th>
                                            <th>Hari</th>
                                            <th>Kode Sekolah</th>
                                            <th>Aktif</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tbody_akd_jadwal_pelajaran">
                                        <?php foreach ($akd_jadwal_pelajarans as $akd_jadwal_pelajaran) : ?>
                                            <tr>
                                                <td width="5">
                                                    <input type="checkbox" class="flat-red check" name="id[]" value="<?= $akd_jadwal_pelajaran->id_jadwal_pelajaran; ?>">
                                                </td>

                                                <td><?= _ent($akd_jadwal_pelajaran->periode . " " . $akd_jadwal_pelajaran->semester); ?></td>

                                                <td><?= _ent($akd_jadwal_pelajaran->kode_jadwal); ?></td>
                                                <td><?= _ent($akd_jadwal_pelajaran->nama_rombel); ?></td>

                                                <td><?= _ent($akd_jadwal_pelajaran->nama_mata_pelajaran); ?></td>

                                                <td><?= _ent($akd_jadwal_pelajaran->nama_ruangan); ?></td>

                                                <td><?= _ent($akd_jadwal_pelajaran->nama_guru); ?></td>

                                                <!-- <td><?= _ent($akd_jadwal_pelajaran->paralel); ?></td> 
                                                <td><?= _ent($akd_jadwal_pelajaran->jadwal_serial); ?></td>  -->
                                                <td><?= _ent($akd_jadwal_pelajaran->jam_mulai); ?></td>
                                                <td><?= _ent($akd_jadwal_pelajaran->jam_akhir); ?></td>

                                                <td><?= _ent($akd_jadwal_pelajaran->hari); ?></td>
                                                <td><?= _ent($akd_jadwal_pelajaran->kode_sekolah); ?></td>

                                                <td><?= _ent($akd_jadwal_pelajaran->status_keaktifan); ?></td>

                                                <td width="200">
                                                    <?php is_allowed('akd_jadwal_pelajaran_view', function () use ($akd_jadwal_pelajaran) { ?>
                                                        <a href="<?= site_url('administrator/akd_absensi_siswa/add/' . $akd_jadwal_pelajaran->id_jadwal_pelajaran); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= "Absensi"; ?>
                                                        <?php }) ?>
                                                        <br>
                                                        <?php is_allowed('akd_jadwal_pelajaran_update', function () use ($akd_jadwal_pelajaran) { ?>
                                                            <a href="<?= site_url('administrator/akd_absensi_siswa/add/' . $akd_jadwal_pelajaran->id_jadwal_pelajaran); ?>" class="label-default"><i class="fa fa-edit "></i> <?= 'Jurnal Guru'; ?></a>
                                                        <?php }) ?>
                                                        <br>
                                                        <!-- <?php is_allowed('akd_jadwal_pelajaran_view', function () use ($akd_jadwal_pelajaran) { ?>
                                                            <a href="<?= site_url('administrator/akd_jadwal_pelajaran/view/' . $akd_jadwal_pelajaran->id_jadwal_pelajaran); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                                                            <?php }) ?> -->
                                                        <?php is_allowed('akd_jadwal_pelajaran_update', function () use ($akd_jadwal_pelajaran) { ?>
                                                            <a href="<?= site_url('administrator/akd_jadwal_pelajaran/edit/' . $akd_jadwal_pelajaran->id_jadwal_pelajaran); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                                                        <?php }) ?>
                                                        <?php is_allowed('akd_jadwal_pelajaran_delete', function () use ($akd_jadwal_pelajaran) { ?>
                                                            <a href="javascript:void(0);" data-href="<?= site_url('administrator/akd_jadwal_pelajaran/delete/' . $akd_jadwal_pelajaran->id_jadwal_pelajaran); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                                                        <?php }) ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                        <?php if ($akd_jadwal_pelajaran_counts == 0) : ?>
                                            <tr>
                                                <td colspan="100">
                                                    Akd Jadwal Pelajaran data is not available
                                                </td>
                                            </tr>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                            </div>
                    </div>
                    <hr>
                    <!-- /.widget-user -->
                    <div class="row">
                        <div class="col-md-8">
                            <div class="col-sm-2 padd-left-0 ">
                                <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email">
                                    <option value="">Bulk</option>
                                    <option value="delete">Delete</option>
                                </select>
                            </div>
                            <div class="col-sm-2 padd-left-0 ">
                                <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                            </div>
                            <!-- <div class="col-sm-3 padd-left-0  ">
                                <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                            </div>
                            <div class="col-sm-3 padd-left-0 ">
                                <select type="text" class="form-control chosen chosen-select" name="f" id="field">
                                    <option value=""><?= cclang('all'); ?></option>
                                    <option <?= $this->input->get('f') == 'tahun_ajaran' ? 'selected' : ''; ?> value="tahun_ajaran">Tahun Ajaran</option>
                                    <option <?= $this->input->get('f') == 'kode_jadwal' ? 'selected' : ''; ?> value="kode_jadwal">Kode Jadwal</option>
                                    <option <?= $this->input->get('f') == 'rombel' ? 'selected' : ''; ?> value="rombel">Rombel</option>
                                    <option <?= $this->input->get('f') == 'id_pelajaran' ? 'selected' : ''; ?> value="id_pelajaran">Id Pelajaran</option>
                                    <option <?= $this->input->get('f') == 'ruangan' ? 'selected' : ''; ?> value="ruangan">Ruangan</option>
                                    <option <?= $this->input->get('f') == 'guru_pengajar' ? 'selected' : ''; ?> value="guru_pengajar">Guru Pengajar</option>
                                    <option <?= $this->input->get('f') == 'paralel' ? 'selected' : ''; ?> value="paralel">Paralel</option>
                                    <option <?= $this->input->get('f') == 'jadwal_serial' ? 'selected' : ''; ?> value="jadwal_serial">Jadwal Serial</option>
                                    <option <?= $this->input->get('f') == 'rentang_jam_pelajaran' ? 'selected' : ''; ?> value="rentang_jam_pelajaran">Rentang Jam Pelajaran</option>
                                    <option <?= $this->input->get('f') == 'hari' ? 'selected' : ''; ?> value="hari">Hari</option>
                                    <option <?= $this->input->get('f') == 'kode_sekolah' ? 'selected' : ''; ?> value="kode_sekolah">Kode Sekolah</option>
                                    <option <?= $this->input->get('f') == 'aktif' ? 'selected' : ''; ?> value="aktif">Aktif</option>
                                </select>
                            </div>
                            <div class="col-sm-1 padd-left-0 ">
                                <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                                    Filter
                                </button>
                            </div>
                            <div class="col-sm-1 padd-left-0 ">
                                <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/akd_jadwal_pelajaran'); ?>" title="<?= cclang('reset_filter'); ?>">
                                    <i class="fa fa-undo"></i>
                                </a>
                            </div> -->
                        </div>
                        </form>
                        <div class="col-md-4">
                            <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate">
                                <?= $pagination; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <!--/box body -->
            </div>
            <!--/box -->
        </div>
    </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
    $(document).ready(function() {

        $('.remove-data').click(function() {

            var url = $(this).attr('data-href');

            swal({
                    title: "<?= cclang('are_you_sure'); ?>",
                    text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
                    cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
                    closeOnConfirm: true,
                    closeOnCancel: true
                },
                function(isConfirm) {
                    if (isConfirm) {
                        document.location.href = url;
                    }
                });

            return false;
        });


        $('#apply').click(function() {

            var bulk = $('#bulk');
            var serialize_bulk = $('#form_akd_jadwal_pelajaran').serialize();

            if (bulk.val() == 'delete') {
                swal({
                        title: "<?= cclang('are_you_sure'); ?>",
                        text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
                        cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
                        closeOnConfirm: true,
                        closeOnCancel: true
                    },
                    function(isConfirm) {
                        if (isConfirm) {
                            document.location.href = BASE_URL + '/administrator/akd_jadwal_pelajaran/delete?' + serialize_bulk;
                        }
                    });

                return false;

            } else if (bulk.val() == '') {
                swal({
                    title: "Upss",
                    text: "<?= cclang('please_choose_bulk_action_first'); ?>",
                    type: "warning",
                    showCancelButton: false,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Okay!",
                    closeOnConfirm: true,
                    closeOnCancel: true
                });

                return false;
            }

            return false;

        }); /*end appliy click*/


        //check all
        var checkAll = $('#check_all');
        var checkboxes = $('input.check');

        checkAll.on('ifChecked ifUnchecked', function(event) {
            if (event.type == 'ifChecked') {
                checkboxes.iCheck('check');
            } else {
                checkboxes.iCheck('uncheck');
            }
        });

        checkboxes.on('ifChanged', function(event) {
            if (checkboxes.filter(':checked').length == checkboxes.length) {
                checkAll.prop('checked', 'checked');
            } else {
                checkAll.removeProp('checked');
            }
            checkAll.iCheck('update');
        });

    }); /*end doc ready*/
</script>