<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
    //This page is a result of an autogenerated content made by running test.html with firefox.
    function domo() {

        // Binding keys
        $('*').bind('keydown', 'Ctrl+e', function assets() {
            $('#btn_edit').trigger('click');
            return false;
        });

        $('*').bind('keydown', 'Ctrl+x', function assets() {
            $('#btn_back').trigger('click');
            return false;
        });

    }


    jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Akd Jadwal Pelajaran <small><?= cclang('detail', ['Akd Jadwal Pelajaran']); ?> </small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class=""><a href="<?= site_url('administrator/akd_jadwal_pelajaran'); ?>">Akd Jadwal Pelajaran</a></li>
        <li class="active"><?= cclang('detail'); ?></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">

        <div class="col-md-12">
            <div class="box box-warning">
                <div class="box-body ">

                    <!-- Widget: user widget style 1 -->
                    <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="widget-user-header ">

                            <div class="widget-user-image">
                                <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                            </div>
                            <!-- /.widget-user-image -->
                            <h3 class="widget-user-username">Akd Jadwal Pelajaran</h3>
                            <h5 class="widget-user-desc">Detail Akd Jadwal Pelajaran</h5>
                            <hr>
                        </div>
                        <div class="form-horizontal" name="form_akd_jadwal_pelajaran" id="form_akd_jadwal_pelajaran">

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Id Jadwal Pelajaran </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->id_jadwal_pelajaran); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Tahun Ajaran/Semester </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->semester); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Kode Guru Pengajar </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->kode_jadwal); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Rombongan Belajar </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->nama_rombel); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Mata Pelajaran </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->nama_mata_pelajaran); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Ruangan </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->nama_ruangan); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Guru Pengajar </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->nama_guru); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Paralel </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->paralel); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Jadwal Serial </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->jadwal_serial); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Rentang Jam Pelajaran </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->jam_ke); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Hari </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->hari); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Kode Sekolah </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->kode_sekolah); ?>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="content" class="col-sm-2 control-label">Aktif </label>

                                <div class="col-sm-8">
                                    <?= _ent($akd_jadwal_pelajaran->status_keaktifan); ?>
                                </div>
                            </div>

                            <br>
                            <br>

                            <div class="view-nav">
                                <?php is_allowed('akd_jadwal_pelajaran_update', function () use ($akd_jadwal_pelajaran) { ?>
                                    <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit akd_jadwal_pelajaran (Ctrl+e)" href="<?= site_url('administrator/akd_jadwal_pelajaran/edit/' . $akd_jadwal_pelajaran->id_jadwal_pelajaran); ?>"><i class="fa fa-edit"></i> <?= cclang('update', ['Akd Jadwal Pelajaran']); ?> </a>
                                <?php }) ?>
                                <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/akd_jadwal_pelajaran/'); ?>"><i class="fa fa-undo"></i> <?= cclang('go_list_button', ['Akd Jadwal Pelajaran']); ?></a>
                            </div>

                        </div>
                    </div>
                </div>
                <!--/box body -->
            </div>
            <!--/box -->

        </div>
    </div>
</section>
<!-- /.content -->