
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Guru      <small><?= cclang('detail', ['Guru']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/guru'); ?>">Guru</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Guru</h3>
                     <h5 class="widget-user-desc">Detail Guru</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_guru" id="form_guru" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id Guru </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->id_guru); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NIP </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->nip); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Password </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->password); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Guru </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->nama_guru); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis Kelamin </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->jenis_kelamin); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tempat Lahir </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->tempat_lahir); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal Lahir </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->tanggal_lahir); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NIK </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->nik); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NIY NIGK </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->niy_nigk); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NUPTK </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->nuptk); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Kepegawaian </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->status_kepegawaian); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jenis PTK </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->jenis_ptk); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pengawas Bidang Studi </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->pengawas_bidang_studi); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Agama </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->agama); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Alamat </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->alamat_jalan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RT </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->rt); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">RW </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->rw); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Dusun </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->nama_dusun); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Desa/Kelurahan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->desa_kelurahan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kecamatan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->kecamatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kode POS </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->kode_pos); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Telepon </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->telepon); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">HP </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->hp); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tugas Tambahan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->tugas_tambahan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Keaktifan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->status_keaktifan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SK CPNS </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->sk_cpns); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tanggal CPNS </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->tanggal_cpns); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SK Pengangkatan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->sk_pengangkatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TMT Pengangkatan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->tmt_pengangkatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Lembaga Pengangkatan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->lembaga_pengangkatan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Golongan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->golongan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Keahlian Laboratorium </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->keahlian_laboratorium); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sumber Gaji </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->sumber_gaji); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Ibu Kandung </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->nama_ibu_kandung); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status Pernikahan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->id_status_pernikahan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Nama Suami/Istri </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->nama_suami_istri); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NIP Suami/Istri </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->nip_suami_istri); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pekerjaan Suami/Istri </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->pekerjaan_suami_istri); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TMT PNS </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->tmt_pns); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Lisensi Kepsek </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->lisensi_kepsek); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Jumlah Sekolah Binaan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->jumlah_sekolah_binaan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Diklat Kepengawasan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->diklat_kepengawasan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Mampu Handle KK </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->mampu_handle_kk); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Keahlian Braille </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->keahlian_breile); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Keahlian Bahasa Isyarat </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->keahlian_bahasa_isyarat); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NPWP </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->npwp); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Kewarganegaraan </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->kewarganegaraan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Foto </label>
                        <div class="col-sm-8">
                             <?php if (is_image($guru->foto)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/guru/' . $guru->foto; ?>">
                                <img src="<?= BASE_URL . 'uploads/guru/' . $guru->foto; ?>" class="image-responsive" alt="image guru" title="foto guru" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/guru/' . $guru->foto; ?>">
                                 <img src="<?= get_icon_file($guru->foto); ?>" class="image-responsive" alt="image guru" title="foto <?= $guru->foto; ?>" width="40px"> 
                               <?= $guru->foto ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Home Base Sekolah </label>

                        <div class="col-sm-8">
                           <?= _ent($guru->kode_sekolah); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('guru_update', function() use ($guru){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit guru (Ctrl+e)" href="<?= site_url('administrator/guru/edit/'.$guru->id_guru); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Guru']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/guru/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Guru']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
